# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry', '~> 0.15'
gem 'puma', '~> 6.6'
gem 'rack-contrib', '~> 2.5'
gem 'rackup', '~> 2.2'
gem 'sinatra'
gem 'sinatra-validation', path: File.join(__FILE__, '../..')
