# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry', '~> 0.15'
gem 'puma', '~> 6.6'
gem 'rack-contrib', '~> 2.5'
gem 'rackup', '~> 2.2'
gem 'rack', '>= 2.2.14'
gem 'sinatra', '>= 4.1.0'
gem 'sinatra-validation', path: '..'
