version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: install deps
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - run: bundle exec rake spec
